# Generated by Django 4.0 on 2022-01-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=2000000000000)),
                ('title', models.TextField()),
                ('done', models.BooleanField(default=False)),
            ],
        ),
    ]
