# Generated by Django 4.0 on 2022-01-29 13:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_is_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
